# Generated by Django 4.2 on 2023-04-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_rename_user_id_todo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completion_at',
            field=models.DateField(default=None),
        ),
    ]
